# Generated by Django 5.2 on 2025-04-29 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dni', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnunciadoEjercicio',
            fields=[
                ('id_enun_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion_ejercicio', models.IntegerField()),
                ('enunciado_ejerc', models.TextField()),
                ('estructura_tablas', models.TextField()),
                ('nombre_ejercicio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id_error', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('penalizacion_llm', models.IntegerField()),
                ('penalizacion_prof', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_realizacion', models.DateField()),
                ('asignatura', models.CharField(max_length=100)),
                ('convocatoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioAlumno',
            fields=[
                ('id_ejercicio_alum', models.AutoField(primary_key=True, serialize=False)),
                ('url_foto_ejerc', models.URLField(max_length=500)),
                ('ocr_imag_to_text', models.TextField()),
                ('correcto_ocr', models.BooleanField(default=False)),
                ('correccion_ocr_hum', models.TextField()),
                ('calif_profesor_solo', models.IntegerField()),
                ('enunciado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejercicios_alumno', to='core.enunciadoejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='enunciadoejercicio',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enunciados', to='core.examen'),
        ),
        migrations.CreateModel(
            name='AlumnoErrorEjercicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion', models.CharField(choices=[('Correcto', 'Correcto'), ('Incorrecto', 'Incorrecto'), ('Anadido', 'Añadido')], max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.alumno')),
                ('ejercicio_alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ejercicioalumno')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.error')),
            ],
            options={
                'unique_together': {('alumno', 'error', 'ejercicio_alumno')},
            },
        ),
    ]
