# Generated by Django 5.2 on 2025-05-09 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fails', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('email', 'date')},
            },
        ),
    ]
